<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Omnex150" name="TestCases.TC001to4_Login_UserCreation_AssignModuleAdmin" tests="5" failures="0" timestamp="22 Apr 2019 13:42:07 GMT" time="256.354" errors="1">
  <testcase name="login" time="17.037" classname="TestCases.TC001to4_Login_UserCreation_AssignModuleAdmin"/>
  <testcase name="login" time="8.621" classname="TestCases.TC001to4_Login_UserCreation_AssignModuleAdmin"/>
  <testcase name="login" time="121.579" classname="TestCases.TC001to4_Login_UserCreation_AssignModuleAdmin">
    <error type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
	at Utilities.Reporter.reportStep(Reporter.java:34)
	at Utilities.Reporter.reportStep(Reporter.java:44)
	at CommonMethods.SeMethods.type(SeMethods.java:117)
	at Pages.LoginPage.login(LoginPage.java:40)
	at TestCases.TC001to4_Login_UserCreation_AssignModuleAdmin.login(TC001to4_Login_UserCreation_AssignModuleAdmin.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- login -->
  <testcase name="login" time="66.428" classname="TestCases.TC001to4_Login_UserCreation_AssignModuleAdmin"/>
  <testcase name="login" time="42.689" classname="TestCases.TC001to4_Login_UserCreation_AssignModuleAdmin"/>
</testsuite> <!-- TestCases.TC001to4_Login_UserCreation_AssignModuleAdmin -->
